# -*- coding: utf-8 -*-
"""Desafio Python - TERA + XP - Fabiana

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uh_5oqGwML6pGn4ZPepu_AMjw4YyFt-w

# Desafio Python - TERA + XP

Olá! Que bom que você veio!<br>
**INSTRUÇÕES**
- Leia com atenção os enunciados
- Se estiver com dúvida veja se as dicas que colocamos podem te ajudar
- Se continuar com dúvida não tenha receio de reassistir a aula ou procurar no Google (Ex: `Como selecionar o primeiro elemento de uma lista em Python`)
- **Não** coloque apenas o resultado. (Ex: `cubo=512` ou `primeiro_elemento='Arroz'`). Queremos ver a sua resolução!

### EXEMPLO) Considere que a aresta deste cubo tem 8cm. Calcule o volume total dessa peça. Guarde o resultado na variável `cubo`.

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Hexahedron.jpg/280px-Hexahedron.jpg)


Dica: Volume de um cubo é sua aresta elevada a terceira potência.
"""

#Coloque sua resposta aqui
cubo = 8**3
cubo

"""
### 1) Considere que o lado `a` deste retângulo tem 5cm e o lado `b`tem 8cm. Calcule a área total dessa peça. Guarde o resultado na variável `retangulo`.

![image](https://upload.wikimedia.org/wikipedia/commons/3/3a/Rectangle.png)


**Dica:** A área do retângulo é = `a * b`

"""

#Coloque sua resposta aqui
retangulo = 5*8
retangulo

"""## Lista de compras
Abaixo você encontrará a lista de compras que trabalharemos nos próximos exercícios.

**Rode a célula contento a lista `lista_compras` antes de continuar**

### Faça os exercícios de **2** a **5** com essa lista.
"""

#Rode essa célula

lista_compras = ['Arroz', 'Feijão', 'Óleo', 'Sal', 'Açúcar','Café', 'Macarrão',
                'Milho', 'Farinha de trigo','Leite', 'Manteiga', 'Ovos']

"""### 2) Guarde na variável `quinto_elemento` o quinto elemento da lista `lista_compras`

**Dica:** Lembre-se. que o Python começa a contar à partir do zero
"""

#Coloque sua resposta aqui

quinto_elemento = lista_compras[4]
quinto_elemento

"""### 3) Guarde na variável `primeiros_itens` uma lista com os 6 primeiros itens da lista."""

#Coloque sua resposta aqui
primeiros_itens = lista_compras[0:6]
primeiros_itens

"""### 4) Insira na lista já existente `lista_compras` o item: `'Batata'`"""

#Coloque sua resposta aqui

lista_compras.append('Batata')
lista_compras

"""### 5) Guarde na variável `quantidade_compras` a quantidade de elementos da lista `lista_compras`

**Dica:** você pode utilizar a função `len()`
"""

#Coloque sua resposta aqui
quantidade_compras = len(lista_compras)
print(quantidade_compras)

"""## Lista de preços
Abaixo você encontrará uma lista de preços que trabalharemos nos próximos exercícios.

**Rode a célula contento a lista `lista_precos` antes de continuar**

### Faça os exercícios de **6** e **7** com essa lista.
"""

#Rode essa célula

lista_precos = [30.5, 20.2, 19.99, 9.99, 192.10, 81,10, 42.42]

"""### 6) Guarde na variável `total` a soma total da lista `lista_precos`"""

#Coloque sua resposta
total = sum([0 ,1, 2, 3, 4, 5, 6, 7])
print(total)

"""### 7) Guarde na variável `precos_dobro` uma nova lista que seja a lista `lista_precos` com seus elementos multiplicados por 2.

**Dica:** utilize **list comprehension**
"""

#Coloque sua resposta aqui
for precos_dobro in lista_precos:
    print(precos_dobro*2)

"""### Dicionários

A **Escala de Scoville** é usda para medir o grau de ardência das pimentas. Preparamos um dicionário com o nome da pimenta e sua respectiva ardência em unidades Scoville.

**Rode a célula contento o dicionário de `pimentas` antes de continuar**

### Faça os exercícios de **8** e **9** seguintes operações com o dicionário `pimentas`
"""

#Rode essa célula
pimentas = {
    'Pimentão': 0,
    'Pepperoncini': 300,
    'Molho Tabasco Jalapenho': 700,
    'Pimenta Anaheim': 750	,
    'Pimenta Poblano': 1250,
    'Pimenta Rocotillo': 2000,
    'Molho Tabasco': 3750,
    'Pimenta Jalapeño': 5250,
    'Wax Pepper': 7500,
    'Molho Tabasco Habanero': 7500,
    'Pimenta Dedo de Moça': 10000,
    'Pimenta Serrano': 16500,
    'Pimenta Malagueta': 75000,
    'Jamaican Hot Pepper': 150000,
    'Habanero Chili': 225000,
    'Pimenta de Chili Scotch Bonnet': 225000,
    'Habanero Chili Red Savina': 463500,
    'Dorset Naga': 923000,
    'Pimenta Naga Bhut Jolokia': 927500,
    'Pimenta Infinity Chilli': 1000000,
    'Pimenta Naga Viper': 1300000,
    'Pimenta Trinidad Scorpion Butch T': 1604615,
    'Vicnic-1313': 1820000,
    'Carolina Reaper': 1884650
}

"""### 8) Guarde na variável `quente` o valor de ardência da pimenta `Carolina Reaper`"""

#Coloque sua resposta aqui
quente = (pimentas['Carolina Reaper'])
print(quente)

"""### 9) Insira no dicionário `pimentas` este novo par: `'Pimenta Caiena': 40000`
**Atenção** não recrie o dicionário, apenas adicione o elemento no dicionário existente
"""

#Coloque sua resposta aqui

pimentas['Pimenta Caiena'] = 40000
print(pimentas)

"""## Funções e condicionais

### 10) Queremos selecionar palavras acima de 10 caracteres. Vamos criar uma função `calcular_palavra` que recebe uma palavra como parâmetro e tenha o retorno de acordo com a tabela abaixo

| Tamanho da palavra (em caracteres)  | Retorno       |
|-----------------|----------------|
| Abaixo de 10  | Tente uma palavra maior |
| Entre 11 e 20 | Boa palavra    |
| Acima de 21   | Uau!|

**Dica 1:** Neste exercício você precisa usar tanto `def` para construir função quanto o `if` para fazer a lógica condicional. (Ex.: `def calcular_palavra(palavra):`)

**Dica 2:** Se a função que você constuiu está correta você terá o seguinte resultado para o código abaixo:<br>
`calcular_palavra('eu')`<br>
-- **`'Tente uma palavra maior'`**<br>

`calcular_palavra('documentação')`<br>
-- **`'Boa palavra'`**<br>

**Dica 3:** Você pode usar a função `len()` para calcular o tamanho de uma palavra, Ex.:<br>
`len('Python')`<br>
-- **6** 
"""

#Coloque sua resposta aqui
def calcular_palavra(palavra ='documentação'):
  if len(palavra) < 10:
    print('Tente uma palavra maior')
  elif len(palavra) <=20:
    print('Boa Palavra')
  else:
    print('Uau')
calcular_palavra()

"""### Com base na sua função faça os exercícios de **11** a **13**:

### 11) Guarde na variável `palavra1` o retorno da função `calcular_palavra` para a palavra **educação**:
"""

def calcular_palavra(palavra1 ='educação'):
  return len(palavra1)
calcular_palavra()

"""### 12) Guarde na variável `palavra2` o retorno da função `calcular_palavra` para a palavra **chave**:"""

#Coloque sua resposta aqui
def calcular_palavra(palavra2 ='chave'):
  return len(palavra2)
calcular_palavra()

"""### 13) Guarde na variável `palavra3` o retorno da função `calcular_palavra` para a palavra **inconstitucionalidades**:"""

#Coloque sua resposta aqui
def calcular_palavra(palavra3 ='inconstitucionalidades'):
  return len(palavra3)
calcular_palavra()

"""## Pandas
#### Faça o download do `.csv` abaixo e faça a leitura dele no `pandas` guarde-a na variável `gorjetas`

[Arquivo para download](https://drive.google.com/file/d/18f43p3FPmzRqN-I5S03U5pn6wdburrZQ/view?usp=sharing)

**Dica 1:** Não se esqueça de importar a biblioteca pandas<br>
**Dica 2:** Leia o material da aula de pandas para aprender como importar um arquivo para ser usado no Google Colab

### Faça os exercícios de **14** a **16** com o DataDrame `gorjetas`

### 14) Guarde na variável `media_contas` o valor da média da colula **total**
"""

#Coloque sua resposta aqui
import pandas as pd
pd.read_csv("/gorjeta.csv")
gorjetas = pd.read_csv("/gorjeta.csv")
media_contas = gorjetas['total'].mean()
gorjetas['total'].mean()

"""### 15) Guarde na variável `max_tamanho` o maior valor da colula **tamanho**

"""

#Coloque sua resposta aqui
max_tamanho = gorjetas['tamanho'].max()
gorjetas['tamanho'].max()

"""### 16) Guarde na variável `min_gorjeta` o menor valor da colula **gorjeta**"""

#Coloque sua resposta aqui
min_gorjeta = gorjetas['gorjeta'].min()
gorjetas['gorjeta'].min()

"""## Debugging
### 17) Encontre e arrume o erro do código abaixo:
"""

idades = {
    'Michael Scott': 43,
    'Pam Beesly': 24,
    'Jim Halpert': 25
}
michael = f'Michael Scott tem {idades["Michael Scott"]} anos de idade.'
print(michael)

idades = {
    'Michael Scott': 43,
    'Pam Beesly': 24,
    'Jim Halpert': 25
}
michael = f'Michael Scott tem {idades["Michael Scott"]} anos de idade.'
print(michael)